# Generated by Django 4.1.4 on 2022-12-13 03:30

from django.db import migrations, models
import projectapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_remove_video_dislikes_alter_video_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='videos/default.mp4', upload_to=projectapp.models.upload_to, verbose_name='Video'),
        ),
    ]
